version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
  app:
    ports:
      - "80:8000"
    build:
      context: ./test_itk
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
